apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: pipeline-dev-quarkus
  name: pipeline-dev-quarkus-birth-api
spec:
  params:
  - name: app_name
    value: birth-api
  - name: git-url
    value: git@github.com:spanishirsh/ogcio-poc.git
  - name: git-revision
    value: main
  - name: context_dir
    value: birth-api
  pipelineRef:
    name: pipeline-dev-quarkus
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
  - name: pipeline-m2-cache
    persistentVolumeClaim:
      claimName: pipeline-m2-cache
  - name: output
    persistentVolumeClaim:
      claimName: pipeline-workspace-pvc
