apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
    pipeline.openshift.io/started-by: seravat
  labels:
    tekton.dev/pipeline: pipeline-dev-quarkus
  name: pipeline-dev-quarkus-j0jh24
  namespace: info-mediator
spec:
  params:
  - name: app_name
    value: gro-api
  - name: git-url
    value: git@github.com:spanishirsh/ogcio-poc.git
  - name: git-revision
    value: main
  - name: context_dir
    value: gro-api
  pipelineRef:
    name: pipeline-dev-quarkus
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
  - name: pipeline-m2-cache
    persistentVolumeClaim:
      claimName: pipeline-m2-cache
  - name: pipeline-jbang-cache
    persistentVolumeClaim:
      claimName: pipeline-jbang-cache
  - name: output
    persistentVolumeClaim:
      claimName: pipeline-workspace-pvc
