apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
    pipeline.openshift.io/started-by: seravat
  labels:
    app: karavan-pipeline-dev-quarkus
    app.kubernetes.io/name: karavan-pipeline-dev-quarkus
    app.kubernetes.io/part-of: karavan
    app.kubernetes.io/version: 3.20.1
    app.openshift.io/runtime: camel
    karavan-project-id: simple-log
    tekton.dev/pipeline: karavan-pipeline-dev-quarkus
  name: karavan-pipeline-dev-quarkus-e5raz2
  namespace: joao-test
spec:
  params:
  - name: PROJECT_ID
    value: simple-log
  pipelineRef:
    name: karavan-pipeline-dev-quarkus
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
  - name: karavan-m2-cache
    persistentVolumeClaim:
      claimName: karavan-m2-cache
  - name: karavan-jbang-cache
    persistentVolumeClaim:
      claimName: karavan-jbang-cache
