apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: karavan-test-mvn
    app.kubernetes.io/name: karavan-test-mvn
    app.kubernetes.io/part-of: karavan-test-mvn
    app.openshift.io/runtime: camel
  name: karavan-test-mvn
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: karavan-test-mvn
      app.kubernetes.io/part-of: karavan-test-mvn
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: karavan-test-mvn
        app.kubernetes.io/name: karavan-test-mvn
        app.kubernetes.io/part-of: karavan-test-mvn
        app.openshift.io/runtime: camel
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/info-mediator/karavan-test:20230812111353
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: simple-log
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
